[package]
name = "typescript-artel-converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
tree-sitter = "0.20.10"
tree-sitter-typescript = "0.20.2"
